class ExceptionDemo11 
{
	public static void main(String[] args) 
	{
		try{
			System.out.println("hello");
		}
		catch(ArithmeticException  t){
			System.out.println("Hi World!");
		}
		
	}
}
