class ExceptionDemo1 
{
	public static void main(String[] args) 
	{
		System.out.println("Hello World-1!");
		System.out.println("Hello World-2!");
		try{
		    int  x=Integer.parseInt(args[0]);  
			int  y=Integer.parseInt(args[1]);
		System.out.println(x/y);
		}catch(ArithmeticException  ae){
			
		}
		catch(NumberFormatException e){
			
		}
		catch(ArrayIndexOutOfBoundsException a){
			
		}
		System.out.println("Hello World-4!");
		System.out.println("Hello World-5!");
	}
}
